---
- name: create profile
  command: >
    ipython profile create {{ipython_profile_name}}
  args:
    creates: '{{ansible_env.HOME}}/.ipython/profile_{{ipython_profile_name}}/ipython_notebook_config.py'

- name: set notebook base_url
  when: ipython_notebook_base_url is defined
  lineinfile: dest={{ansible_env.HOME}}/.ipython/profile_{{ipython_profile_name}}/ipython_notebook_config.py regex="# c.NotebookApp.base_url = '/'" insertafter="c.NotebookApp.base_url = '{{ipython_notebook_endpoint}}'
